name: CI Python Pipeline

# ¿Cuándo se ejecuta el robot? Cuando hagas push a la rama 'main'
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest # El robot usará una máquina con Linux temporal

    steps:
    # 1. El robot clona tu repositorio (tu código)
    - name: Checkout del código
      uses: actions/checkout@v4

    # 2. El robot instala Python
    - name: Configurar Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3. El robot instala las dependencias de tu proyecto
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. El robot revisa que tu código no tenga errores fatales de sintaxis
    - name: Revisión de sintaxis (Linting básico)
      run: |
        pip install flake8
        # Esto revisa la carpeta scripts/ buscando errores de código (detiene el proceso si hay errores críticos)
        flake8 scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics